---
apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: test-app
spec:
  limits:
    - default:
        cpu: 0.25
        memory: 256Mi
      defaultRequest:
        cpu: 0.125
        memory: 128Mi
      type: Container